catalog/urls.py
from django.urls import path
from django.conf.urls import url
from django.urls import include, re_path
from . import views
from django_filters.views import FilterView
from catalog.filters import BookFilter
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^search/$', FilterView.as_view(filterset_class=BookFilter,
    template_name='catalog/result.html'), name='search'),    

    path('books/', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    ]

urlpatterns += [   
    path('mybooks/', views.ReadingListView.as_view(), name='reading_list'),
]

urlpatterns += [   
    path('add_book/', login_required(views.add_book), name='add_book'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_genre/', views.add_genre, name='add_genre'),
    path('add_language/', views.add_language, name='add_language'),
]

urlpatterns += [
    path('add_to_wish_list/', views.add_to_wish_list, name='add_to_wish_list'),
    path('add_to_reading/', views.add_to_reading, name='add_to_reading'),
    path('add_to_completed/', views.add_to_completed, name='add_to_completed'),
    path('check_status/', views.check_status, name='check_status'),
]

from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns += [
    path('xbooks/', views.BookList.as_view()),
    path('xbook/<int:pk>/', views.BookDetail.as_view()),

    path('xauthors/', views.AuthorList.as_view()),
    path('xauthor/<int:pk>/', views.AuthorDetail.as_view()),

    path('xgenres/', views.GenreList.as_view()),
    path('xgenre/<int:pk>/', views.GenreDetail.as_view()),

    path('xlanguages/', views.LanguageList.as_view()),
    path('xlanguage/<int:pk>/', views.LanguageDetail.as_view()),


]

urlpatterns = format_suffix_patterns(urlpatterns)

personal_book_manager/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework import routers
from catalog import views


urlpatterns = [
    path('admin/', admin.site.urls),
]
# Use include() to add paths from the catalog application 
from django.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls')),
    
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User    
from datetime import date, timedelta
# Create your models here.
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)',unique=True)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

from django.urls import reverse # Used to generate URLs by reversing the URL patterns

import datetime
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    CONDITIONS = (
        ('g','Good'),
        ('b','Bad'),
        ('f','fine'),
    )
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ManyToManyField('Author', related_name="author", help_text='author(s)')
    translator = models.ForeignKey('Author', related_name="translator",on_delete=models.SET_NULL, null=True,blank=True)
    language = models.ForeignKey('Language',related_name="language", on_delete=models.SET_NULL, null=True)
    translation = models.ForeignKey('Language', related_name="translation",on_delete=models.SET_NULL, null=True,blank=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book',null=True,blank=True)
    YEAR_CHOICES = [(r,r) for r in range(1800, datetime.date.today().year+1)]
    pub_year = models.IntegerField(('year'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    condition = models.CharField(max_length=1,choices = CONDITIONS,blank=True, default='g')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    archive =  models.BooleanField(default=False, help_text='In store')
    class Meta:
        ordering = ['title','-pub_year']

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    def display_author(self):
        """Create a string for the Author. This is required to display author in Admin."""
        return ', '.join(author.first_name for author in self.author.all()[:3])

    display_author.short_description = 'Author'
    display_genre.short_description = 'Genre'

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100,null=True,blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    class Meta:
        ordering = ['first_name','last_name']
    
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name}'

class ReadingList(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    @property
    def is_reading(self):
        if self.status=='r':
            return True
        return False
    @property
    def is_completed(self):
        if self.status=='c':
            return True
        return False
    @property
    def is_wish(self):
        if self.status=='w':
            return True
        return False


    STATUS = (
        ('r', 'Reading'),
        ('c', 'Completed'),
        ('w', 'Wish List'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='w',
        help_text='Reading List')

    class Meta:
        ordering = ['book']

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",unique=True)

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

catalog/views.py
from django.shortcuts import render,HttpResponse
from catalog.models import Book, Author, Genre, Language,    ReadingList,User
from django.views import generic
from rest_framework import generics
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django import forms
from django.utils import timezone
from catalog.forms import BookForm,AuthorForm,GenreForm,LanguageForm


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()

    num_genres = Book.objects.all().aggregate(Count('genre',distinct=True))  
    context = {
        'num_books': num_books,
        'num_authors': num_authors,
        'num_genres': num_genres['genre__count'],
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['books'] = Book.objects.filter(author=self.object.pk) | Book.objects.filter(translator=self.object.pk)

            return context

from django.views import View


from .filters import BookFilter


class SearchListView(generic.ListView):
    model = Book
    template_name = "catalog/result.html"

    def get_context_data(self,**kwargs):
        context = super.get_context_data(**kwargs)
        context['filter'] = BookFilter(self.request.GET,queryset=self.get_queryset())
        return context
def search(request):
    book_list = Book.objects.all()
    book_filter = BookFilter(request.GET, queryset=book_list)
    return render(request, 'catalog/result.html', {'filter': book_filter})

class ReadingListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = ReadingList
    template_name ='catalog/book_list_reading_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return ReadingList.objects.filter(reader=self.request.user)

from datetime import date, timedelta

class NewBooksListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = Book
    template_name ='catalog/new_arrivals.html'
    paginate_by = 10
    

    def get_queryset(self):        
        return Book.objects.all()




def add_book(request):
     
    if request.method == "POST":
        form = BookForm(request.POST)

        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/')
 
    else:
 
        form = BookForm()
 
        return render(request, "catalog/add_book.html", {'form': form})



def add_author(request):
     
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/')
 
    else:
 
        form = AuthorForm()
 
        return render(request, "catalog/add_author.html", {'form': form})

def add_genre(request):
     
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/')
 
    else:
 
        form = GenreForm()
 
        return render(request, "catalog/add_genre.html", {'form': form})

def add_language(request):
    from django.core.exceptions import ValidationError
    if request.method == "POST":
        form = LanguageForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/')
    else: 
        form = LanguageForm() 
        return render(request, "catalog/add_language.html", {'form': form})

from django.http import JsonResponse

def add_to_wish_list(request):
    id_book = request.GET.get('id_book', None)
    id_user = request.GET.get('id_user', None)

    book_ins = Book.objects.get(id=int(id_book))
    user_ins = User.objects.get(id=int(id_user))
    if ReadingList.objects.filter(reader=user_ins,book=book_ins).exists():
        data = {
            'status': 'Already in Wish List!'
            }
    elif ReadingList.objects.filter(reader=user_ins,book=book_ins,status='c').exists():
        data = {
            'status': 'Already Completed!'
            }
    elif ReadingList.objects.filter(reader=user_ins,book=book_ins,status='r').exists():
        data = {
            'status': 'Already Reading!'
            }

    else:
        item = ReadingList(reader=user_ins,book=book_ins,status='w')
        item.save()

        data = {
            'status': 'Added to Wish List!'
            }
    return JsonResponse(data)

def add_to_reading(request):
    id_book = request.GET.get('id_book', None)
    id_user = request.GET.get('id_user', None)

    book_ins = Book.objects.get(id=int(id_book))
    user_ins = User.objects.get(id=int(id_user))

    if ReadingList.objects.filter(reader=user_ins,book=book_ins,status='r').exists():
        data = {
            'status': 'Already Reading!'
            }
    elif ReadingList.objects.filter(reader=user_ins,book=book_ins,status='c').exists():
        data = {
            'status': 'Already Completed!'
            }
    else:
        wish_list_ins = ReadingList.objects.filter(reader=user_ins,book=book_ins,status='w')
        if wish_list_ins.exists():
            wish_list_ins.delete()
        item = ReadingList(reader=user_ins,book=book_ins,status='r')
        item.save()

        data = {
            'status': 'Added to Reading List!'
            }
    return JsonResponse(data)

def add_to_completed(request):    
    id_book = request.GET.get('id_book', None)
    id_user = request.GET.get('id_user', None)

    book_ins = Book.objects.get(id=int(id_book))
    user_ins = User.objects.get(id=int(id_user))

    if ReadingList.objects.filter(reader=user_ins,book=book_ins,status='w').exists():
        data = {
            'status': 'You have not read this book!'
            }
    elif ReadingList.objects.filter(reader=user_ins,book=book_ins,status='r'):
        reading_ins = ReadingList.objects.filter(reader=user_ins,book=book_ins,status='r')
        reading_ins.delete()

        item = ReadingList(reader=user_ins,book=book_ins,status='c')
        item.save()

        data = {
            'status': 'Added to Completed!'
            }
    else:
        data = {
            'status': 'No action performed!'
            }

    return JsonResponse(data)

def check_status(request):    
    id_book = request.GET.get('id_book', None)
    id_user = request.GET.get('id_user', None)
    book_ins = Book.objects.get(id=int(id_book))
    user_ins = User.objects.get(id=int(id_user))

    if ReadingList.objects.filter(reader=user_ins,book=book_ins).exists():
        list_ins = ReadingList.objects.get(reader=user_ins,book=book_ins)
        data = {
            'status': list_ins.status
            }
    else:
        data = {
            'status': 'No Status'
            }
    return JsonResponse(data)



from .serializers import BookSerializer, AuthorSerializer, GenreSerializer, LanguageSerializer

class BookList(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer



class AuthorList(generics.ListCreateAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


class AuthorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


class GenreList(generics.ListCreateAPIView):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer


class GenreDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer


class LanguageList(generics.ListCreateAPIView):
    queryset = Language.objects.all()
    serializer_class = LanguageSerializer


class LanguageDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Language.objects.all()
    serializer_class = LanguageSerializer

catalog/templates/catalog/add_author.html
{% extends "base_form.html" %}
{% load widget_tweaks %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      <li class="breadcrumb-item"><a href="{% url 'index' %}" class="text-white">Home</a></li>
      <li class="breadcrumb-item text-white active" aria-current="page">Add Author</li>
    </ol>
</nav>

<form method="POST" action="{% url 'add_author' %}" id="certform">
            {% csrf_token %}
        <div class="well">
          <h4 style="margin-top: 0">Add Author</h4>
          <div class="row">
              {% for field in form.visible_fields %}
              <div class="form-group col-sm-4 col-md-3">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}    
          </div>
          <div><input type="submit"  class="btn btn-dark" value="Upload"/></div>
          
        </div>
      </form>
      <script>
            $(document).ready(function () {
               $('#certform').ajaxForm(function () {
               window.close();
               window.opener.location.reload();
               });
            });
         </script>      
      
{% endblock %}

catalog/templates/catalog/add_book.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}
{% block content %}
<script>
  $('.datepicker').datepicker();
</script>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      <li class="breadcrumb-item"><a href="{% url 'index' %}" class="text-white">Home</a></li>
      <li class="breadcrumb-item text-white active" aria-current="page">Add Book</li>
    </ol>
</nav>

<form method="post" action="{% url 'add_book' %}">
    {% csrf_token %}
    <div class="well">
      <h4 style="margin-top: 0">Welcome My New Book!</h4>
      <div class="row">
          {% for field in form.visible_fields %}
          <div class="form-group col-sm-2">
              
                {% ifequal field.label 'Pur date' %}
                <label for="{{ field.id_for_label }}">Purchasing Date</label>
                {% else %}             
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% endifequal %} 
                {{ field|add_class:'form-control ' }}
                {% ifequal field.label 'Translation' %}
                <a href="{% url 'add_language'%}" target="popup" onclick="window.open('{% url 'add_language' %}','name','width=600,height=400')">Add Language</a>
                {% endifequal %} 
                {% ifequal field.label 'Language' %}
                <a href="{% url 'add_language'%}" target="popup" onclick="window.open('{% url 'add_language' %}','name','width=600,height=400')">Add Language</a>
                {% endifequal %} 
                {% ifequal field.label 'Author' %}
                <a href="{% url 'add_author'%}" target="popup" onclick="window.open('{% url 'add_author' %}','name','width=600,height=400')">Add Author</a>
                {% endifequal %} 
                {% ifequal field.label 'Translator' %}
                <a href="{% url 'add_author'%}" target="popup" onclick="window.open('{% url 'add_author' %}','name','width=600,height=400')">Add Author</a>
                {% endifequal %} 
                {% ifequal field.label 'Genre' %}
                <a href="{% url 'add_genre'%}" target="popup" onclick="window.open('{% url 'add_genre' %}','name','width=600,height=400')">Add Genre</a>
                {% endifequal %}    
                    
          </div>
        {% endfor %}    
      </div>
      <button type="submit" class="btn btn-dark">Add Book</button>
  
    </div>
  </form>

{% endblock %}

catalog/templates/catalog/add_genre.html
{% extends "base_form.html" %}
{% load widget_tweaks %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      <li class="breadcrumb-item"><a href="{% url 'index' %}" class="text-white">Home</a></li>
      <li class="breadcrumb-item text-white active" aria-current="page">Add Genre</li>
    </ol>
</nav>
<form method="post"  action="{% url 'add_genre' %}" id="certform">
        {% csrf_token %}
        <div class="well">
          <h4 style="margin-top: 0">Add Genre</h4>
          <div class="row">
              {% for field in form.visible_fields %}
              <div class="form-group col-sm-4 col-md-3">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}    
          </div>
          <div><input type="submit"  class="btn btn-dark" value="Upload"/></div>
      
        </div>
      </form>
      <script>
            $(document).ready(function () {
               $('#certform').ajaxForm(function () {
               window.close();
               window.opener.location.reload();
               });
            });
         </script>      
      
      
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      <li class="breadcrumb-item "><a href="{% url 'index' %}" class="text-white">Home</a></li>
      <li class="breadcrumb-item "><a href="{% url 'books' %}" class="text-white">Books</a></li>
      <li class="breadcrumb-item active text-white" aria-current="page">{{book.title}}</li>
    </ol>
  </nav>

  <div class="card">
      <div class="card-body">
          <div class="d-flex w-100 justify-content-between">
              <h2 class="card-title">{{book.title}}</h2>
              <small class="text-info"><strong>{{book.language}}</strong>{% if book.translation %}/{{book.translation}}{% endif %}</small>
          </div>
          {% ifequal book.author.all.count 1 %}
          <h5 class="card-subtitle mb-2"><a href="{% url 'author-detail' book.author.all.0.pk %}" class="card-link">{{ book.author.all|first }}</a></h5>         
          {% else %}
            {% for author in book.author.all %}
            {% if forloop.last %}
              ,
            {% endif %}
            <h5 class="card-subtitle mb-2"><a href="{% url 'author-detail' author.pk %}" class="card-link">{{author}}</a></h5>
              {% endfor %}
          {% endifequal %}

            {% if book.translator %}
              <a href="{% url 'author-detail' book.translator.pk %}" class="card-link">{{book.translator}}</a> 
            {% endif %}          
            <p class="card-text" style="text-align:justify;">{{book.summary}}</p>
            {% for genre in book.genre.all %}
           <span class="badge badge-info">{{genre}}</span>      
            {% endfor %}
            {% if user.is_authenticated %}
            <span class="badge badge-info" id="wish_badge" style="float:right;display: none;">From Wish List</span>      
            <span class="badge badge-danger" id="reading_badge" style="float:right;display: none;">Currently Reading</span>      
            <span class="badge badge-success" id="completed_badge" style="float:right;display: none;">Completed</span>      
            {% endif%}

      </div>
    
      <div class="card-footer">
        {% if book.pub_year %}
        <p class="card-text">  This book was published in {{book.pub_year}}.</p>
        {% endif %}
        {% if book.owner %}
        <p class="card-text">  This book is owned by {{book.owner}}.</p>
        {% endif %}
        {% if user.is_authenticated %}
          {% if book.archive %}
          <p class="card-text">  This book is in archives now.</p>
          {% endif%} 
        {% endif%} 
        {% ifequal book.condition 'g' %}
        <p class="card-text">Condition: <span class="badge badge-success">{{ book.get_condition_display|capfirst }}</span></p>  
        {% endifequal %}
        {% ifequal book.condition 'b' %}
        <p class="card-text">Condition: <span class="badge badge-danger">{{ book.get_condition_display|capfirst }}</span></p>  
        {% endifequal %}
        {% ifequal book.condition 'f' %}
        <p class="card-text">Condition: <span class="badge badge-warning">{{ book.get_condition_display|capfirst }}</span></p>  
        {% endifequal %}  
      </div>    
  </div>

  

  {% if user.is_authenticated %}

  <div class="row" id="wish_list_div" style="display:none">
      <div class="col-sm-2">
        <form method="get">
            <input type="number" name="id_book" id="id_book" value="{{book.id}}" style="display:none;">                   
            <input type="number" name="id_user" id="id_user" value="{{user.id}}" style="display:none;">                   
            <button type="button" id="wish_list"class="btn btn-info btn-md">Add To Wish List</button>
          </form>      
      </div>
    </div>
    <div class="row" id="reading_div" style="display:none">
        <div class="col-sm-2">
          <form method="get">
              <input type="number" name="id_book" id="id_book" value="{{book.id}}" style="display:none;">                   
              <input type="number" name="id_user" id="id_user" value="{{user.id}}" style="display:none;">                   
              <button type="button" id="reading_list"class="btn btn-danger btn-md">Add To Reading List</button>
            </form>      
        </div>
      </div>
      <div class="row" id="completed_div" style="display:none">
          <div class="col-sm-2">
            <form method="get">
                <input type="number" name="id_book" id="id_book" value="{{book.id}}" style="display:none;">                   
                <input type="number" name="id_user" id="id_user" value="{{user.id}}" style="display:none;">                   
                <button type="button" id="completed_list"class="btn btn-success btn-md">Add To Completed</button>
              </form>      
          </div>
        </div>
      


  <script>
  $( document ).ready(function() {
        var id_user = $('#id_user').val();
        var id_book = $('#id_book').val();
    
        $.ajax({
          url: '{% url "check_status" %}',
          data: {
            'id_user': id_user,
            'id_book': id_book,
          },
          dataType: 'json',
          success: function (data) {
              if(data['status']=='w'){
                $("#wish_badge").css('display','block');
                $("#reading_div").css('display','block');
                $("#completed_div").css('display','block');
              }
              else if(data['status']=='r'){
                $("#reading_badge").css('display','block');
                $("#completed_div").css('display','block');
              }
              else if(data['status']=='c'){
                $("#completed_badge").css('display','block');
              }
              else{
                $("#wish_list_div").css('display','block');
                $("#reading_div").css('display','block');

              }
          }
        });
  
      });
    </script>
{% endif %}

  <script>
      $("#wish_list").click(function () {
        $("#wish_list_div").css('display','none');
        $("#wish_badge").css('display','block');
        var id_user = $('#id_user').val();
        var id_book = $('#id_book').val();
  
        $.ajax({
          url: '{% url "add_to_wish_list" %}',
          data: {
            'id_user': id_user,
            'id_book': id_book,
          },
          dataType: 'json',
          success: function (data) {
             alert(data['status']);
          }
        });
  
      });
    </script>
  <script>
      $("#reading_list").click(function () {
        $("#wish_list_div").css('display','none');
        $("#reading_div").css('display','none');
        $("#wish_badge").css('display','none');
        $("#reading_badge").css('display','block');
        var id_user = $('#id_user').val();
        var id_book = $('#id_book').val();
  
        $.ajax({
          url: '{% url "add_to_reading" %}',
          data: {
            'id_user': id_user,
            'id_book': id_book,
          },
          dataType: 'json',
          success: function (data) {
              alert(data['status']);
          }
        });
  
      });
    </script>
  <script>
      $("#completed_list").click(function () {
        $("#wish_list_div").css('display','none');
        $("#reading_div").css('display','none');
        $("#completed_div").css('display','none');
        $("#reading_badge").css('display','none');
        $("#completed_badge").css('display','block');
        var id_user = $('#id_user').val();
        var id_book = $('#id_book').val();
  
        $.ajax({
          url: '{% url "add_to_completed" %}',
          data: {
            'id_user': id_user,
            'id_book': id_book,
          },
          dataType: 'json',
          success: function (data) {
              alert(data['status']);
          }
        });
  
      });
    </script>



    {% endblock %}

catalog/templates/catalog/book_list_reading_user.html
{% extends "base_generic.html" %}

{% block content %}
<nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-dark">
          <li class="breadcrumb-item "><a href="{% url 'index' %}" class="text-white">Home</a></li>
          <li class="breadcrumb-item active text-white" aria-current="page">Your Lists</li>
        </ol>
      </nav>
    
{% if user.is_authenticated %}
<div class="h4">{{ user.get_username|capfirst}}'s Reading List  </div>
{% endif %}

    {% if readinglist_list %}
    <ul class="list-group">

      {% for bookinst in readinglist_list %} 
      <li class="list-group-item">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> 
        {% if bookinst.is_reading %}
        <span class="badge badge-danger">{{ bookinst.get_status_display }}</span>        
        {% endif%}
        {% if bookinst.is_completed %}
        <span class="badge badge-success">{{ bookinst.get_status_display }}</span>        
        {% endif%}
        {% if bookinst.is_wish %}
        <span class="badge badge-info">{{ bookinst.get_status_display }}</span>        
        {% endif%}

      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Hurry up! Grab a book from <a href="{% url 'books'%}">Catalog</a>!.</p>
    {% endif %}       
{% endblock %}